name: Service Status Monitor

on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:

jobs:
  health_check:
    runs-on: ubuntu-latest
    name: 服务健康检查
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 执行健康检查
        run: |
          chmod +x ./health-check.sh
          ./health-check.sh
          
      - name: 查看状态报告
        run: cat status.json
